# This is a basic workflow to help you get started with Actions

name: Q2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: teste creation nouveau fichier
        run: | 
          date > Q2_archive_TOTO.txt
          echo "CHAMPVILLARD SÉBASTIEN" >> Q2_archive_TOTO.txt
          cat TOTO.txt >> Q2_archive_TOTO.txt
          wc TOTO.txt
        
        # push
      - name: commmit et push
        run: |
          git config --global user.name sebeaty
          git config --global user.email sebachamp007@outlook.fr
          git add Q2_archive_TOTO.txt
          git commit -m "test push de Q2_archive_TOTO.txt"
          git push
